version: '3.8'

services:
  web:
    image: oxydizer/sethreads-api:latest  # Use the image you built
    platform: linux/amd64  # Specify the architecture explicitly
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_POSTGRESQL_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require