"""Add Table for home page

Revision ID: e5f20708e6eb
Revises: 44cd0e667db7
Create Date: 2024-09-25 17:36:18.991235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f20708e6eb'
down_revision: Union[str, None] = '44cd0e667db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('comments')
    op.drop_table('subcomments')
    op.drop_table('threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_by', sa.VARCHAR(), nullable=True),
    sa.Column('course_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.VARCHAR(), nullable=True),
    sa.Column('is_highlight', sa.BOOLEAN(), nullable=True),
    sa.Column('create_at', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['create_by'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subcomments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('reply_of', sa.INTEGER(), nullable=True),
    sa.Column('reply_data', sa.VARCHAR(), nullable=True),
    sa.Column('posted_by', sa.VARCHAR(), nullable=True),
    sa.Column('create_at', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['students.student_id'], ),
    sa.ForeignKeyConstraint(['reply_of'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment_from', sa.INTEGER(), nullable=True),
    sa.Column('comment_data', sa.VARCHAR(), nullable=True),
    sa.Column('posted_by', sa.VARCHAR(), nullable=True),
    sa.Column('create_at', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['comment_from'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('student_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('is_ta', sa.BOOLEAN(), nullable=True),
    sa.Column('picture', sa.BLOB(), nullable=True),
    sa.Column('ta_course_id', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
